require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/categories", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Admin::Category. As you add validations to Admin::Category, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Admin::Category.create! valid_attributes
      get admin_categories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      category = Admin::Category.create! valid_attributes
      get admin_category_url(category)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_category_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      category = Admin::Category.create! valid_attributes
      get edit_admin_category_url(category)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Admin::Category" do
        expect {
          post admin_categories_url, params: { admin_category: valid_attributes }
        }.to change(Admin::Category, :count).by(1)
      end

      it "redirects to the created admin_category" do
        post admin_categories_url, params: { admin_category: valid_attributes }
        expect(response).to redirect_to(admin_category_url(Admin::Category.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Admin::Category" do
        expect {
          post admin_categories_url, params: { admin_category: invalid_attributes }
        }.to change(Admin::Category, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_categories_url, params: { admin_category: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_category" do
        category = Admin::Category.create! valid_attributes
        patch admin_category_url(category), params: { admin_category: new_attributes }
        category.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the admin_category" do
        category = Admin::Category.create! valid_attributes
        patch admin_category_url(category), params: { admin_category: new_attributes }
        category.reload
        expect(response).to redirect_to(admin_category_url(category))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        category = Admin::Category.create! valid_attributes
        patch admin_category_url(category), params: { admin_category: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested admin_category" do
      category = Admin::Category.create! valid_attributes
      expect {
        delete admin_category_url(category)
      }.to change(Admin::Category, :count).by(-1)
    end

    it "redirects to the admin_categories list" do
      category = Admin::Category.create! valid_attributes
      delete admin_category_url(category)
      expect(response).to redirect_to(admin_categories_url)
    end
  end
end
